[tool.black]
line-length=120
target-version = ['py37']

[tool.isort]
profile = "black"
line_length = 120
force_sort_within_sections = true
combine_as_imports = true

[tool.mypy]
python_version = 3.7
ignore_missing_imports = true
show_error_context = true
show_column_numbers = true
show_error_codes = true
pretty = true
exclude = '\.eggs|\.git|\.mypy_cache|\.tox|build|dist|data|env|venv'
